[package]
name = "afrxo/compulse"
description = "Class-based components made easy."
version = "1.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "default.project.json", "LICENSE"]

[dependencies]